INSERT INTO book (title, author, publisher, release_date, genre, category, synopsis) VALUES
('Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 'Alfred A. Knopf', '2022-07-05', 'Literary Fiction', 'Fiction', 'A moving story about friendship, creativity, and love, centered on two video game designers who reunite to build worlds together and navigate success and heartbreak.'),
('The Midnight Library', 'Matt Haig', 'Canongate Books', '2020-08-13', 'Fantasy / Philosophical', 'Fiction', 'Nora Seed enters a magical library where each book represents a different version of her life, forcing her to confront regret, possibility, and the meaning of happiness.'),
('Project Hail Mary', 'Andy Weir', 'Ballantine Books', '2021-05-04', 'Science Fiction', 'Fiction', 'A lone astronaut wakes up on a spaceship with no memory — and must save humanity from extinction with the help of an unexpected alien ally.'),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Atria Books', '2017-06-13', 'Historical Fiction', 'Fiction', 'Aging Hollywood icon Evelyn Hugo tells her scandalous life story — and the truth behind her seven marriages — to an unknown journalist.'),
('Educated', 'Tara Westover', 'Random House', '2018-02-20', 'Memoir', 'Non-fiction', 'A woman raised by survivalist parents in rural Idaho escapes her isolated upbringing through education, eventually earning a PhD from Cambridge University.'),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'Harper', '2015-02-10', 'History / Anthropology', 'Non-fiction', 'An exploration of how Homo sapiens evolved from insignificant apes into the dominant species shaping the planet through culture and cooperation.'),
('Atomic Habits', 'James Clear', 'Avery', '2018-10-16', 'Self-Help / Psychology', 'Non-fiction', 'A practical guide to building better habits, breaking bad ones, and mastering the small behaviors that lead to remarkable results.'),
('The Song of Achilles', 'Madeline Miller', 'Ecco Press', '2011-09-20', 'Mythological Fiction', 'Fiction', 'A retelling of the Greek myth of Achilles from the perspective of his companion Patroclus, exploring love, destiny, and war.'),
('Becoming', 'Michelle Obama', 'Crown Publishing', '2018-11-13', 'Autobiography', 'Non-fiction', 'The former First Lady reflects on her life, from her Chicago childhood to her years in the White House, exploring identity, purpose, and public service.'),
('Klara and the Sun', 'Kazuo Ishiguro', 'Alfred A. Knopf', '2021-03-02', 'Dystopian / Science Fiction', 'Fiction', 'An artificial friend named Klara observes human behavior as she awaits adoption, offering a poignant reflection on love, technology, and consciousness.');